// ============================================================
// expose-ops.js — Vue template bindings: management & workflow
// Manager, alerts, time report, WO requests, forecasting,
// create WO, inventory, purchasing
// (Open Orders + Completed Orders bindings live in expose-shipping.js)
// ============================================================

import * as store from './libs/store.js';
import { enterPoReceiveView, enterWoRequestView, enterCreateWoView,
         enterWoForecastingView,
         saveHeaderLinks, saveSplashLinks } from './pages/splash-view.js';
import { openManagerSection, loadKpiData, loadDelayedOrders,
         fetchPriorityOrders, updatePriority, updateAssignedOperator,
         handleAssignChange, submitCustomAssign, cancelCustomAssign,
         openNotesPanel, loadManagerAlerts,
         sendAiMessage, loadTimeReport,
         loadWoProblems, openWoProblemModal, closeWoProblemModal, confirmResolveWoProblem,
         loadResolvedWoProblems,
         openDelayedWoDetail, closeDelayedWoDetail } from './pages/manager-view.js';
import { openAlertResolve, submitAlertResolve } from './pages/manager-alerts.js';
import { loadPoReceiveOrders, openPoReceiveItem, closePoReceiveItem, submitPoReceive,
         loadPoReceivedOrders, unreceivePoOrder,
         enterInventoryAdjustView, searchItemMasterPart, submitManualCount,
         loadPoDetailRealCount } from './pages/inventory-view.js';
import { enterSubassySetup, clearSubassySearch, runSubassySearch, toggleUnitChildren,
         openComponentUsedOn, closeComponentUsedOn } from './pages/subassy-setup.js';
import { loadWoRequests, submitWoRequestForm, deleteWoRequestItem,
         saveWoRequestDetail, sendToManagerApproval, toggleWoRequestOnHold, saveWoRequestStatusNote,
         saveWoRequestSalesOrder, saveWoRequestInlineFields,
         checkWoRequestPartMatch, acceptSoHint, dismissSoHint,
         openSendToForecast, closeSendToForecast, submitSendToForecast } from './pages/wo-request-view.js';
import { openWoRequestDetail, closeWoRequestDetail, dismissWoRequestDetail,
         handleWoFileUploadForRequest, openSubpartWoForm,
         inspectSubpart, finishSubpartInspect, cancelSubpartInspect } from './pages/wo-request-detail.js';
import { moveWoRequestToOrder, moveOrderToWoRequest, deleteOrderFromDetail } from './pages/request-convert.js';
import { loadForecastedItems,
         openDeleteConfirm, cancelDeleteForecast, confirmDeleteForecast,
         openMoveBackConfirm, cancelMoveBack, confirmMoveBack } from './pages/wo-forecasting-view.js';
import { loadCreateWoItems, setAlereWoNumber, switchCreateWoTab, loadCreatedWoItems } from './pages/create-wo-view.js';
import { loadPurchasingOrders, switchPurchasingTab,
         loadPurchasingCompleted, loadOrderEvents,
         openNewRequestForm, closeNewRequestForm, submitPurchasingRequest,
         onPurchasingPartBlur,
         openOrderDetail, closeOrderDetail, saveOrderDetail,
         loadPartUsageForOrder } from './pages/purchasing-view.js';
import { saveSteelField, saveSteelQuotes, addSteelQuote, toggleBestQuote, removeSteelQuote,
         toggleSteelStatusPicker, setSteelStatus,
         selectSteelQuoteForOrder, closeSteelOrderPanel, confirmSteelOrder,
         uploadSteelQuoteFile, openSteelQuoteFile, removeSteelQuoteFile } from './pages/purchasing-steel.js';
import { checkPoActiveOrders, isPoPartDuplicated } from './pages/purchasing-request-checks.js';
import { completeOrder, submitReceiving } from './pages/purchasing-receive.js';
import { enterApprovalTab, approveOrder, cancelRevise, submitRevise } from './pages/purchasing-approval.js';
import { enterWoApprovalView, exitWoApprovalView, loadManagerPendingWoRequests,
         openManagerWoDetail, closeManagerWoDetail, saveManagerWoDetail,
         removeManagerSubpart, managerFinalApproveWo,
         openManagerWoSendBack, cancelManagerWoSendBack,
         submitManagerWoSendBack,
         loadManagerWoFiles, handleManagerWoFileUpload,
         handleManagerWoFileDelete,
         openManagerSubpartFiles, closeManagerSubpartFiles } from './pages/wo-manager-approval.js';
import { uploadOrderAttachment, deleteOrderAttachment, loadOrderAttachments,
         loadPurchasingPartFiles } from './pages/purchasing-attachments.js';
import { openQuoteBuilder, closeQuoteBuilder, toggleQuoteOrder, submitQuote,
         stageQuoteFile, unstageQuoteFile,
         loadAllQuotes, openQuoteOrder, cancelQuoteOrder, submitQuoteOrder,
         loadOrderQuotes, saveQuote, addQuoteRow, removeQuoteRow } from './pages/purchasing-quotes-view.js';
import { openSupplierCatalogFromHistory, loadSupplierCatalog,
         clearSupplierCatalog } from './pages/purchasing-research.js';
import { openRfqDraft, closeRfqDraft, copyRfqDraft,
         addOrderToRfq, removeOrderFromRfq } from './pages/purchasing-rfq.js';
import { enterPurchasingView, enterPoRequestView, enterApprovalQueueView } from './pages/splash-view.js';
import { enterPoForecastingView, exitPoForecastingView, loadPoForecast,
         openPoForecastDeleteConfirm, cancelPoForecastDelete, confirmPoForecastDelete,
         openPoForecastMoveBack, cancelPoForecastMoveBack, confirmPoForecastMoveBack,
         openPoForecastSend, closePoForecastSend, submitPoForecastSend,
         openForecastOrderDetail, checkForecastRevisits } from './pages/purchasing-forecast.js';

export function buildOpsExpose() {
    return {
        // Manager AI chat
        aiChatOpen:     store.aiChatOpen,
        aiChatLoading:  store.aiChatLoading,
        aiChatInput:    store.aiChatInput,
        aiChatMessages: store.aiChatMessages,

        // Manager
        assignCustomInput:    store.assignCustomInput,
        managerSubView:       store.managerSubView,
        priorityDept:         store.priorityDept,
        priorityOrders:       store.priorityOrders,
        delayedOrders:        store.delayedOrders,
        delayedOrdersByDept:  store.delayedOrdersByDept,
        kpiStats:             store.kpiStats,
        kpiByOperator:        store.kpiByOperator,
        kpiCycleTime:         store.kpiCycleTime,
        kpiHoldReasons:       store.kpiHoldReasons,
        kpiOldestWos:         store.kpiOldestWos,
        managerAlerts:        store.managerAlerts,
        delayedWoCount:       store.delayedWoCount,
        managerAlertCount:    store.managerAlertCount,
        managerTotalBadge:    store.managerTotalBadge,

        // WO Problems
        woProblems:                 store.woProblems,
        woProblemCount:             store.woProblemCount,
        woProblemModalOpen:         store.woProblemModalOpen,
        woProblemTarget:            store.woProblemTarget,
        woProblemResolution:        store.woProblemResolution,
        woProblemResolutionError:   store.woProblemResolutionError,
        woProblemResolverName:      store.woProblemResolverName,
        woProblemResolverNameError: store.woProblemResolverNameError,
        resolvedWoProblems:         store.resolvedWoProblems,

        // Manager functions
        openManagerSection, loadKpiData, loadDelayedOrders,
        fetchPriorityOrders, updatePriority, updateAssignedOperator,
        handleAssignChange, submitCustomAssign, cancelCustomAssign,
        openNotesPanel, loadManagerAlerts,
        sendAiMessage, loadTimeReport,
        delayedWoDetailOpen: store.delayedWoDetailOpen,
        delayedWoDetail:     store.delayedWoDetail,
        openDelayedWoDetail, closeDelayedWoDetail,
        loadWoProblems, openWoProblemModal, closeWoProblemModal, confirmResolveWoProblem,
        loadResolvedWoProblems,
        alertResolveOpen:      store.alertResolveOpen,
        alertResolveTarget:    store.alertResolveTarget,
        alertResolveType:      store.alertResolveType,
        alertResolveBy:        store.alertResolveBy,
        alertResolveByError:   store.alertResolveByError,
        alertResolveText:      store.alertResolveText,
        alertResolveTextError: store.alertResolveTextError,
        openAlertResolve, submitAlertResolve,

        // Time Report
        timeReportSessions:     store.timeReportSessions,
        timeReportFrom:         store.timeReportFrom,
        timeReportTo:           store.timeReportTo,
        timeReportTab:          store.timeReportTab,
        timeReportExpandedWo:   store.timeReportExpandedWo,
        timeReportExpandedPart: store.timeReportExpandedPart,
        timeReportByWo:         store.timeReportByWo,
        timeReportByPart:       store.timeReportByPart,

        // WO Requests
        woRequests:           store.woRequests,
        woRequestsLoading:    store.woRequestsLoading,
        woRequestForm:        store.woRequestForm,
        woRequestFormErrors:  store.woRequestFormErrors,
        woRequestSearch:      store.woRequestSearch,
        filteredWoRequests:   store.filteredWoRequests,
        selectedWoRequest:    store.selectedWoRequest,
        woRequestReadOnly:    store.woRequestReadOnly,
        woRequestDetailForm:  store.woRequestDetailForm,
        woRequestInlineState:        store.woRequestInlineState,
        woRequestSoHint:             store.woRequestSoHint,
        woRequestActiveWoItems:      store.woRequestActiveWoItems,
        woRequestDetailActiveWos:    store.woRequestDetailActiveWos,
        woRequestDefaultsApplied:    store.woRequestDefaultsApplied,
        woRequestHistoryLoading:         store.woRequestHistoryLoading,
        woRequestParentUsageLoading:     store.woRequestParentUsageLoading,
        woRequestHistoryLoading36mo:     store.woRequestHistoryLoading36mo,
        woRequestParentUsageLoading36mo: store.woRequestParentUsageLoading36mo,
        woRequestEstQtyInStock36mo:      store.woRequestEstQtyInStock36mo,
        woRequestSuggestedQty36mo:       store.woRequestSuggestedQty36mo,
        woRequestYearlyAvg36mo:          store.woRequestYearlyAvg36mo,
        woRequestLastMade:               store.woRequestLastMade,
        woRequestRealCount:              store.woRequestRealCount,
        woRequestRealCountLabel:         store.woRequestRealCountLabel,
        woRequestUsedOn:                 store.woRequestUsedOn,
        woRequestUsedOnLoading:          store.woRequestUsedOnLoading,
        woRequestSubparts:             store.woRequestSubparts,
        woRequestSubpartsLoading:      store.woRequestSubpartsLoading,
        woRequestSubpartsExpanded:     store.woRequestSubpartsExpanded,
        woRequestSubpartMode:          store.woRequestSubpartMode,
        woRequestSubpartBins:          store.woRequestSubpartBins,
        woRequestSubpartDescs:         store.woRequestSubpartDescs,
        woRequestSubpartForms:         store.woRequestSubpartForms,
        woRequestSubpartStats:         store.woRequestSubpartStats,
        woRequestSubpartEstHave:       store.woRequestSubpartEstHave,
        isSubpartInspect:              store.isSubpartInspect,
        woRequestSubpartParentLabel:   store.woRequestSubpartParentLabel,
        woRequestMarkAllSubparts:      store.woRequestMarkAllSubparts,
        woRequestEstQtyInStock:      store.woRequestEstQtyInStock,
        woRequestSuggestedQty:       store.woRequestSuggestedQty,
        woRequestStockWarning:       store.woRequestStockWarning,
        enterWoRequestView,
        submitWoRequestForm,
        deleteWoRequestItem,
        openWoRequestDetail,
        closeWoRequestDetail,
        dismissWoRequestDetail,
        openSubpartWoForm,
        inspectSubpart,
        finishSubpartInspect,
        cancelSubpartInspect,
        saveWoRequestDetail,
        sendToManagerApproval,
        toggleWoRequestOnHold,
        saveWoRequestStatusNote,
        saveWoRequestSalesOrder,
        saveWoRequestInlineFields,
        checkWoRequestPartMatch, acceptSoHint, dismissSoHint,
        moveWoRequestToOrder,
        openSendToForecast, closeSendToForecast, submitSendToForecast,
        handleWoFileUploadForRequest,
        sendToForecastOpen:   store.sendToForecastOpen,
        sendToForecastTarget: store.sendToForecastTarget,
        sendToForecastForm:   store.sendToForecastForm,
        sendToForecastErrors: store.sendToForecastErrors,

        // WO Forecasting
        forecastingItems:  store.forecastingItems,
        forecastingLoading: store.forecastingLoading,
        forecastDeleteId:  store.forecastDeleteId,
        forecastMoveBackId: store.forecastMoveBackId,
        enterWoForecastingView, loadForecastedItems,
        openDeleteConfirm, cancelDeleteForecast, confirmDeleteForecast,
        openMoveBackConfirm, cancelMoveBack, confirmMoveBack,

        // Create WO
        createWoItems:       store.createWoItems,
        createWoItemsGrouped: store.createWoItemsGrouped,
        createWoLoading:     store.createWoLoading,
        createWoInlineState: store.createWoInlineState,
        createWoTab:         store.createWoTab,
        createdWoItems:         store.createdWoItems,
        createdWoItemsGrouped:  store.createdWoItemsGrouped,
        enterCreateWoView, loadCreateWoItems, setAlereWoNumber, switchCreateWoTab, loadCreatedWoItems,

        // Inventory
        inventoryMode:          store.inventoryMode,
        // Inventory Adjustment
        inventoryAdjustSearch:   store.inventoryAdjustSearch,
        inventoryAdjustLoading:  store.inventoryAdjustLoading,
        inventoryAdjustSearched: store.inventoryAdjustSearched,
        inventoryAdjustResult:   store.inventoryAdjustResult,
        inventoryAdjustSaving:   store.inventoryAdjustSaving,
        inventoryAdjustForm:     store.inventoryAdjustForm,
        inventoryAdjustErrors:   store.inventoryAdjustErrors,
        // PO Receive
        poReceiveOrders:           store.poReceiveOrders,
        poReceiveLoading:          store.poReceiveLoading,
        poReceiveTab:              store.poReceiveTab,
        poReceiveOpen:             store.poReceiveOpen,
        poReceiveItem:             store.poReceiveItem,
        poReceiveSaving:           store.poReceiveSaving,
        poReceiveForm:             store.poReceiveForm,
        filteredPoReceiveOrders:   store.filteredPoReceiveOrders,
        poReceiveCounts:           store.poReceiveCounts,
        poReceiveSearch:           store.poReceiveSearch,
        // PO Already Received
        poReceivedOrders:          store.poReceivedOrders,
        poReceivedLoading:         store.poReceivedLoading,
        poReceiveShowReceived:     store.poReceiveShowReceived,
        filteredPoReceivedOrders:  store.filteredPoReceivedOrders,
        poReceivedCounts:          store.poReceivedCounts,
        enterPoReceiveView, enterInventoryAdjustView, searchItemMasterPart, submitManualCount, loadPoDetailRealCount,
        loadPoReceiveOrders, openPoReceiveItem, closePoReceiveItem, submitPoReceive,
        loadPoReceivedOrders, unreceivePoOrder,

        // TEMPORARY: Subassy Setup
        subassySearch:     store.subassySearch,
        subassyLoading:    store.subassyLoading,
        subassyError:      store.subassyError,
        subassyRoot:       store.subassyRoot,
        subassyComponents: store.subassyComponents,
        subassyUsedOnRows: store.subassyUsedOnRows,
        subassyTruncated:  store.subassyTruncated,
        subassyUnitExpanded: store.subassyUnitExpanded,
        subassyPopupOpen: store.subassyPopupOpen, subassyPopupPart: store.subassyPopupPart,
        subassyPopupLoading: store.subassyPopupLoading, subassyPopupRows: store.subassyPopupRows,
        subassyPopupTruncated: store.subassyPopupTruncated,
        enterSubassySetup, clearSubassySearch, runSubassySearch, toggleUnitChildren,
        openComponentUsedOn, closeComponentUsedOn,

        // Purchasing
        purchasingTab:              store.purchasingTab,
        purchasingOrders:           store.purchasingOrders,
        purchasingLoading:          store.purchasingLoading,
        filteredPurchasingOrders:    store.filteredPurchasingOrders,
        steelOrdersByLocation:       store.steelOrdersByLocation,
        partOrdersByLocation:        store.partOrdersByLocation,
        supplyOrdersByLocation:      store.supplyOrdersByLocation,
        poForecastOrdersByLocation:  store.poForecastOrdersByLocation,
        approvalOrdersByLocation:    store.approvalOrdersByLocation,
        steelStatusPickerOpen:      store.steelStatusPickerOpen,
        steelOrderPanelOpen:        store.steelOrderPanelOpen,
        steelOrderSaving:           store.steelOrderSaving,
        steelOrderErrors:           store.steelOrderErrors,
        steelOrderForm:             store.steelOrderForm,
        purchasingTabCounts:        store.purchasingTabCounts,
        purchasingRequestModalOpen:  store.purchasingRequestModalOpen,
        purchasingRequestSaving:     store.purchasingRequestSaving,
        purchasingRequestForm:       store.purchasingRequestForm,
        purchasingRequestFormErrors: store.purchasingRequestFormErrors,
        purchasingRequestActivePoItems: store.purchasingRequestActivePoItems,
        purchasingDetailActivePos:      store.purchasingDetailActivePos,
        purchasingDetailOpen:           store.purchasingDetailOpen,
        purchasingDetailOrder:          store.purchasingDetailOrder,
        poDetailRealCount:              store.poDetailRealCount,
        poDetailRealCountLabel:         store.poDetailRealCountLabel,
        purchasingDetailSection:        store.purchasingDetailSection,
        purchasingDetailSaving:         store.purchasingDetailSaving,
        purchasingDetailAutoSaved:      store.purchasingDetailAutoSaved,
        purchasingReceiveSaving:        store.purchasingReceiveSaving,
        purchasingDetailForm:           store.purchasingDetailForm,
        purchasingReceiveForm:          store.purchasingReceiveForm,
        purchasingDetailEvents:         store.purchasingDetailEvents,
        purchasingDetailEventsLoading:  store.purchasingDetailEventsLoading,
        purchasingPartUsage:              store.purchasingPartUsage,
        purchasingPartUsageLoading:       store.purchasingPartUsageLoading,
        purchasingPartParentUsage:        store.purchasingPartParentUsage,
        purchasingPartParentUsageLoading: store.purchasingPartParentUsageLoading,
        purchasingPartEstQtyInStock:      store.purchasingPartEstQtyInStock,
        purchasingPartSuggestedQty:       store.purchasingPartSuggestedQty,
        purchasingPartPurchaseHistory:        store.purchasingPartPurchaseHistory,
        purchasingPartPurchaseHistoryLoading: store.purchasingPartPurchaseHistoryLoading,
        purchasingPartPurchaseHistoryError:   store.purchasingPartPurchaseHistoryError,
        purchasingPartUsage36mo:              store.purchasingPartUsage36mo,
        purchasingPartUsageLoading36mo:       store.purchasingPartUsageLoading36mo,
        purchasingPartParentUsage36mo:        store.purchasingPartParentUsage36mo,
        purchasingPartParentUsageLoading36mo: store.purchasingPartParentUsageLoading36mo,
        purchasingPartEstQtyInStock36mo:      store.purchasingPartEstQtyInStock36mo,
        purchasingPartSuggestedQty36mo:       store.purchasingPartSuggestedQty36mo,
        purchasingPartYearlyAvg36mo:          store.purchasingPartYearlyAvg36mo,
        purchasingDetailQuotes:         store.purchasingDetailQuotes,
        purchasingDetailQuotesLoading:  store.purchasingDetailQuotesLoading,
        orderAttachments:          store.orderAttachments,
        orderAttachmentsLoading:   store.orderAttachmentsLoading,
        orderAttachmentsUploading: store.orderAttachmentsUploading,
        quoteBuilderOpen:            store.quoteBuilderOpen,
        quoteBuilderSaving:          store.quoteBuilderSaving,
        quoteBuilderSelectedOrders:  store.quoteBuilderSelectedOrders,
        quoteBuilderItems:           store.quoteBuilderItems,
        quoteBuilderForm:            store.quoteBuilderForm,
        quoteBuilderPendingFiles:    store.quoteBuilderPendingFiles,
        allQuotes:                   store.allQuotes,
        allQuotesLoading:            store.allQuotesLoading,
        quoteOrderingId:             store.quoteOrderingId,
        quoteOrderPoNum:             store.quoteOrderPoNum,
        quoteOrderSaving:            store.quoteOrderSaving,
        purchasingCompletedOrders:      store.purchasingCompletedOrders,
        purchasingCompletedLoading:     store.purchasingCompletedLoading,
        purchasingCompletedFrom:        store.purchasingCompletedFrom,
        purchasingCompletedTo:          store.purchasingCompletedTo,
        approvalOrders:          store.approvalOrders,
        approvalManagerAuthed:   store.approvalManagerAuthed,
        approvalPinInput:        store.approvalPinInput,
        approvalPinError:        store.approvalPinError,
        approvalReviseOpen:      store.approvalReviseOpen,
        approvalReviseNote:      store.approvalReviseNote,
        // PO Forecasting
        poForecastOrders:     store.poForecastOrders,
        poForecastLoading:    store.poForecastLoading,
        poForecastDeleteId:   store.poForecastDeleteId,
        poForecastMoveBackId: store.poForecastMoveBackId,
        poForecastSendOpen:   store.poForecastSendOpen,
        poForecastSendSaving: store.poForecastSendSaving,
        poForecastSendErrors: store.poForecastSendErrors,
        poForecastSendForm:   store.poForecastSendForm,
        enterPoForecastingView, exitPoForecastingView, loadPoForecast,
        openPoForecastDeleteConfirm, cancelPoForecastDelete, confirmPoForecastDelete,
        openPoForecastMoveBack, cancelPoForecastMoveBack, confirmPoForecastMoveBack,
        openPoForecastSend, closePoForecastSend, submitPoForecastSend,
        openForecastOrderDetail, checkForecastRevisits,

        enterPurchasingView, enterPoRequestView, enterApprovalQueueView, loadPurchasingOrders, switchPurchasingTab,
        loadPurchasingCompleted, loadOrderEvents,
        openNewRequestForm, closeNewRequestForm, submitPurchasingRequest, onPurchasingPartBlur, checkPoActiveOrders, isPoPartDuplicated,
        openOrderDetail, closeOrderDetail, saveOrderDetail, completeOrder, submitReceiving, loadPartUsageForOrder,
        moveOrderToWoRequest, deleteOrderFromDetail,
        loadOrderQuotes, saveQuote, addQuoteRow, removeQuoteRow,
        saveSteelField, saveSteelQuotes, addSteelQuote, toggleBestQuote, removeSteelQuote,
        toggleSteelStatusPicker, setSteelStatus,
        selectSteelQuoteForOrder, closeSteelOrderPanel, confirmSteelOrder,
        uploadSteelQuoteFile, openSteelQuoteFile, removeSteelQuoteFile,
        uploadOrderAttachment, deleteOrderAttachment, loadOrderAttachments, loadPurchasingPartFiles,
        enterApprovalTab, approveOrder, cancelRevise, submitRevise,
        openRfqDraft, closeRfqDraft, copyRfqDraft, addOrderToRfq, removeOrderFromRfq,
        rfqDraftOpen:     store.rfqDraftOpen,
        rfqDraftSubject:  store.rfqDraftSubject,
        rfqDraftText:     store.rfqDraftText,
        rfqDraftHtml:     store.rfqDraftHtml,
        rfqDraftCopied:   store.rfqDraftCopied,
        rfqDraftOrders:   store.rfqDraftOrders,
        rfqPickerOpen:    store.rfqPickerOpen,
        rfqPickerSearch:  store.rfqPickerSearch,
        rfqPickerResults: store.rfqPickerResults,

        // Manager WO Approval Queue
        managerWoApprovalList:    store.managerWoApprovalList,
        managerWoApprovalLoading: store.managerWoApprovalLoading,
        managerWoSelectedRequest: store.managerWoSelectedRequest,
        managerWoDetailForm:      store.managerWoDetailForm,
        managerWoSendBackOpen:    store.managerWoSendBackOpen,
        managerWoSendBackNote:    store.managerWoSendBackNote,
        managerWoApprovalCount:   store.managerWoApprovalCount,
        managerWoSubpartForms:    store.managerWoSubpartForms,
        managerWoSubpartDescs:    store.managerWoSubpartDescs,
        managerWoSubpartFilesOpen:    store.managerWoSubpartFilesOpen,
        managerWoSubpartFilesPart:    store.managerWoSubpartFilesPart,
        managerWoSubpartFiles:        store.managerWoSubpartFiles,
        managerWoSubpartFilesLoading: store.managerWoSubpartFilesLoading,
        enterWoApprovalView, exitWoApprovalView, loadManagerPendingWoRequests,
        openManagerWoDetail, closeManagerWoDetail, saveManagerWoDetail,
        removeManagerSubpart, managerFinalApproveWo,
        openManagerWoSendBack, cancelManagerWoSendBack, submitManagerWoSendBack,
        loadManagerWoFiles, handleManagerWoFileUpload, handleManagerWoFileDelete,
        openManagerSubpartFiles, closeManagerSubpartFiles,

        openQuoteBuilder, closeQuoteBuilder, toggleQuoteOrder, submitQuote,
        stageQuoteFile, unstageQuoteFile,
        loadAllQuotes, openQuoteOrder, cancelQuoteOrder, submitQuoteOrder,
        supplierCatalogLoading:  store.supplierCatalogLoading,
        supplierCatalogParts:    store.supplierCatalogParts,
        supplierCatalogCoid:     store.supplierCatalogCoid,
        supplierCatalogName:     store.supplierCatalogName,
        supplierCatalogSearch:   store.supplierCatalogSearch,
        supplierCatalogChoices:  store.supplierCatalogChoices,
        filteredSupplierCatalog: store.filteredSupplierCatalog,
        openSupplierCatalogFromHistory, loadSupplierCatalog, clearSupplierCatalog,

        // Header / splash quick-link editors
        headerLinks:          store.headerLinks,
        headerLinksModalOpen: store.headerLinksModalOpen,
        headerLinksSaving:    store.headerLinksSaving,
        saveHeaderLinks,
        splashLinks:          store.splashLinks,
        splashLinksModalOpen: store.splashLinksModalOpen,
        splashLinksSaving:    store.splashLinksSaving,
        saveSplashLinks,
    };
}
