// ============================================================
// expose-eng.js — Vue template bindings: engineering domain
// Inquiries, customer follow-up, completed, prints/files
// ============================================================

import * as store from './libs/store.js';
import { ENG_STATUSES, ENG_PRIORITIES, ENG_ASSIGNEES, ENG_RECORD_CATEGORIES,
         ENG_FOLLOWUP_STATUSES, ENG_FOLLOWUP_PRIORITIES, ENG_FOLLOWUP_FIT_STATUSES,
         ENG_FOLLOWUP_STATUS_LABELS, ENG_FOLLOWUP_STATUS_COLORS,
         PART_CHANGE_TYPES, PART_CHANGE_TYPE_LABELS, PART_CHANGE_TYPE_COLORS,
         PART_CHANGE_CHECKLIST_ITEMS } from './libs/config.js';
import { enterPartChangesView, loadPartChanges,
         openPartChangeCreate, closePartChangeCreate, submitPartChangeCreate,
         openPartChangeDetail, closePartChangeDetail,
         setPartChangeChecklistItem, savePartChangeDetail,
         completePartChange, reopenPartChange } from './pages/part-changes-view.js';
import { runBomSearch, clearBomSearch, toggleBomLine,
         startBomLineEdit, cancelBomLineEdit, saveBomLineEdit,
         askBomLineDelete, cancelBomLineDelete, confirmBomLineDelete,
         openBomAdd, cancelBomAdd, submitBomAdd } from './pages/bom-editor.js';
import { enterEngineeringInquiriesView,
         openEngInquiryForm, closeEngInquiryForm, submitEngInquiry,
         handleEngNewInquiryFileSelect, removeEngNewInquiryFile,
         openEngInquiryDetail, closeEngInquiryDetail,
         saveEngInquiry, saveEngInquiryInline, handleEngImageUpload,
         openEngImagesModal, closeEngImagesModal,
         appendEngNote,
         openEngNoteModal, submitEngNoteModal, markActionStepRead,
         openEngDeleteConfirm, closeEngDeleteConfirm, confirmEngDelete,
         onEngStatusChange,
         enterEngCompletedView, loadEngCompletedInquiries,
         restoreEngFromCompleted,
         enterEngPrintsView, searchEngPrintFiles,
         handleEngPrintUpload,
         openEngPrintDeleteConfirm, closeEngPrintDeleteConfirm, confirmEngPrintDelete,
         openEngPrintsReplaceConfirm, closeEngPrintsReplaceConfirm,
         proceedEngPrintsReplaceAll, doEngPrintsReplaceAll,
         openEngPrintsUploadConfirm, closeEngPrintsUploadConfirm,
         proceedEngPrintsUpload } from './pages/engineering-view.js';
import { enterEngineeringFollowupView, loadEngFollowups,
         openEngFollowupCreate, openEngFollowupDetail, closeEngFollowupModal,
         submitEngFollowupCreate, saveEngFollowupDetail,
         submitEngFollowupNote, loadEngFollowupEvents,
         applyFollowupNoAnswer, applyFollowupFitConfirmed, applyFollowupFitFailed,
         submitFollowupCustomerResponded, onFollowupDateShippedChange,
         closeEngFollowupCase } from './pages/engineering-followup.js';

export function buildEngExpose() {
    return {
        // Part-change data shown in the WO Request data panel (engineering-owned
        // even though it renders in the WO Request modal; expose-ops.js is at cap)
        woRequestCalcChain:   store.woRequestCalcChain,
        woRequestChainParts:  store.woRequestChainParts,
        woRequestOpenChanges: store.woRequestOpenChanges,

        // Part Changes
        partChanges:            store.partChanges,
        partChangesLoading:     store.partChangesLoading,
        partChangeSearch:       store.partChangeSearch,
        partChangeStatusFilter: store.partChangeStatusFilter,
        filteredPartChanges:    store.filteredPartChanges,
        partChangeOpenCount:    store.partChangeOpenCount,
        partChangeFormOpen:     store.partChangeFormOpen,
        partChangeSaving:       store.partChangeSaving,
        partChangeForm:         store.partChangeForm,
        partChangeFormErrors:   store.partChangeFormErrors,
        partChangeTypes:        PART_CHANGE_TYPES,
        partChangeTypeLabels:   PART_CHANGE_TYPE_LABELS,
        partChangeTypeColors:   PART_CHANGE_TYPE_COLORS,
        partChangeChecklistItems: PART_CHANGE_CHECKLIST_ITEMS,
        partChangeDetailOpen:     store.partChangeDetailOpen,
        partChangeSelected:       store.partChangeSelected,
        partChangeDetailSaving:   store.partChangeDetailSaving,
        partChangeCheckName:      store.partChangeCheckName,
        partChangeChecklistDone:  store.partChangeChecklistDone,
        enterPartChangesView, loadPartChanges,
        openPartChangeCreate, closePartChangeCreate, submitPartChangeCreate,
        openPartChangeDetail, closePartChangeDetail,
        setPartChangeChecklistItem, savePartChangeDetail,
        completePartChange, reopenPartChange,

        // BOM Lookup tab
        partChangesTab: store.partChangesTab,
        bomSearch:      store.bomSearch,
        bomLoading:     store.bomLoading,
        bomSearched:    store.bomSearched,
        bomParent:      store.bomParent,
        bomParentDesc:  store.bomParentDesc,
        bomLines:         store.bomLines,
        bomTopLevelCount: store.bomTopLevelCount,
        bomEditName:      store.bomEditName,
        bomEditLineId:    store.bomEditLineId,
        bomEditForm:      store.bomEditForm,
        bomEditSaving:    store.bomEditSaving,
        bomDeleteLineId:  store.bomDeleteLineId,
        bomAddOpen:       store.bomAddOpen,
        bomAddForm:       store.bomAddForm,
        bomAddSaving:     store.bomAddSaving,
        runBomSearch, clearBomSearch, toggleBomLine,
        startBomLineEdit, cancelBomLineEdit, saveBomLineEdit,
        askBomLineDelete, cancelBomLineDelete, confirmBomLineDelete,
        openBomAdd, cancelBomAdd, submitBomAdd,

        // Engineering inquiries
        engView:               store.engView,
        engInquiries:          store.engInquiries,
        engInquiriesLoading:   store.engInquiriesLoading,
        engInquirySearch:      store.engInquirySearch,
        engStatusFilter:       store.engStatusFilter,
        engPriorityFilter:     store.engPriorityFilter,
        engAssigneeFilter:     store.engAssigneeFilter,
        engManualSort:         store.engManualSort,
        engInquiryFormOpen:    store.engInquiryFormOpen,
        engInquiryForm:        store.engInquiryForm,
        engInquiryFormErrors:  store.engInquiryFormErrors,
        engNewInquiryFiles:    store.engNewInquiryFiles,
        engSelectedInquiry:    store.engSelectedInquiry,
        engInquiryDetailOpen:  store.engInquiryDetailOpen,
        engImagesModalOpen:    store.engImagesModalOpen,
        engInquiryImages:      store.engInquiryImages,
        engImagesLoading:      store.engImagesLoading,
        filteredEngInquiries:  store.filteredEngInquiries,
        groupedEngInquiries:   store.groupedEngInquiries,
        engCreateCategoryLabel: store.engCreateCategoryLabel,
        engStatuses:           ENG_STATUSES,
        engPriorities:         ENG_PRIORITIES,
        engAssignees:          ENG_ASSIGNEES,
        engRecordCategories:   ENG_RECORD_CATEGORIES,

        // Engineering Follow-Up
        engFollowups:              store.engFollowups,
        engFollowupsLoading:       store.engFollowupsLoading,
        engFollowupSearch:         store.engFollowupSearch,
        engFollowupStatusFilter:   store.engFollowupStatusFilter,
        engFollowupPriorityFilter: store.engFollowupPriorityFilter,
        engFollowupSummary:        store.engFollowupSummary,
        filteredEngFollowups:      store.filteredEngFollowups,
        engFollowupStatuses:       ENG_FOLLOWUP_STATUSES,
        engFollowupPriorities:     ENG_FOLLOWUP_PRIORITIES,
        engFollowupFitStatuses:    ENG_FOLLOWUP_FIT_STATUSES,
        engFollowupStatusLabels:   ENG_FOLLOWUP_STATUS_LABELS,
        engFollowupStatusColors:   ENG_FOLLOWUP_STATUS_COLORS,
        loadEngFollowups,

        // Follow-up modal
        engFollowupModalOpen:     store.engFollowupModalOpen,
        engFollowupModalMode:     store.engFollowupModalMode,
        engFollowupForm:          store.engFollowupForm,
        engFollowupFormErrors:    store.engFollowupFormErrors,
        engFollowupSelected:      store.engFollowupSelected,
        engFollowupActiveTab:     store.engFollowupActiveTab,
        engFollowupEvents:        store.engFollowupEvents,
        engFollowupEventsLoading: store.engFollowupEventsLoading,
        engFollowupNewNote:       store.engFollowupNewNote,
        engFollowupNewNoteBy:     store.engFollowupNewNoteBy,
        engFollowupActionPanel:   store.engFollowupActionPanel,
        engFollowupResponseNote:  store.engFollowupResponseNote,
        engFollowupResponseType:  store.engFollowupResponseType,
        engFollowupChecklistCount: store.engFollowupChecklistCount,
        openEngFollowupCreate, openEngFollowupDetail, closeEngFollowupModal,
        submitEngFollowupCreate, saveEngFollowupDetail,
        submitEngFollowupNote, loadEngFollowupEvents,
        applyFollowupNoAnswer, applyFollowupFitConfirmed, applyFollowupFitFailed,
        submitFollowupCustomerResponded, onFollowupDateShippedChange,
        closeEngFollowupCase,

        // Inquiry actions
        enterEngineeringInquiriesView, enterEngineeringFollowupView,
        openEngInquiryForm, closeEngInquiryForm, submitEngInquiry,
        handleEngNewInquiryFileSelect, removeEngNewInquiryFile,
        openEngInquiryDetail, closeEngInquiryDetail,
        saveEngInquiry, saveEngInquiryInline, handleEngImageUpload,
        openEngImagesModal, closeEngImagesModal,
        engNewEntries: store.engNewEntries,
        appendEngNote,
        openEngNoteModal, submitEngNoteModal, markActionStepRead,
        engNoteModalOpen:    store.engNoteModalOpen,
        engNoteModalContext: store.engNoteModalContext,
        engNoteModalText:    store.engNoteModalText,
        engDeleteConfirmOpen: store.engDeleteConfirmOpen,
        engDeleteTarget:      store.engDeleteTarget,
        openEngDeleteConfirm, closeEngDeleteConfirm, confirmEngDelete,
        onEngStatusChange,

        // Engineering Completed
        engCompletedInquiries: store.engCompletedInquiries,
        engCompletedLoading:   store.engCompletedLoading,
        engCompletedFrom:      store.engCompletedFrom,
        engCompletedTo:        store.engCompletedTo,
        engCompletedSearch:    store.engCompletedSearch,
        filteredEngCompleted:  store.filteredEngCompleted,
        enterEngCompletedView, loadEngCompletedInquiries, restoreEngFromCompleted,

        // Engineering Prints / Files Update
        engPrintsSearch:             store.engPrintsSearch,
        engPrintsFiles:              store.engPrintsFiles,
        engPrintsLoading:            store.engPrintsLoading,
        engPrintsSearchedPart:       store.engPrintsSearchedPart,
        engPrintsDeleteConfirmOpen:  store.engPrintsDeleteConfirmOpen,
        engPrintsDeleteTarget:       store.engPrintsDeleteTarget,
        engPrintsReplaceConfirmOpen: store.engPrintsReplaceConfirmOpen,
        engPrintsUploadConfirmOpen:  store.engPrintsUploadConfirmOpen,
        enterEngPrintsView, searchEngPrintFiles,
        handleEngPrintUpload,
        openEngPrintDeleteConfirm, closeEngPrintDeleteConfirm, confirmEngPrintDelete,
        openEngPrintsReplaceConfirm, closeEngPrintsReplaceConfirm,
        proceedEngPrintsReplaceAll, doEngPrintsReplaceAll,
        openEngPrintsUploadConfirm, closeEngPrintsUploadConfirm, proceedEngPrintsUpload,
    };
}
