// ============================================================
// expose-ops.js — Vue template bindings: management & workflow
// Manager, alerts, time report, WO requests, forecasting,
// create WO, inventory, completed orders, open orders
// ============================================================

import * as store from './libs/store.js';
import { OPEN_ORDER_STATUSES, CHUTE_PART_STATUSES,
         OPEN_ORDER_SORT_FIELDS, INVENTORY_TABS } from './libs/config.js';
import { enterInventoryView, enterPoReceiveView, enterWoRequestView, enterCreateWoView,
         enterOpenOrdersView, enterWoForecastingView,
         saveHeaderLinks, saveSplashLinks } from './pages/splash-view.js';
import { openManagerSection, loadKpiData, loadDelayedOrders,
         fetchPriorityOrders, updatePriority, updateAssignedOperator,
         handleAssignChange, submitCustomAssign, cancelCustomAssign,
         openNotesPanel, loadManagerAlerts,
         sendAiMessage, loadTimeReport,
         loadWoProblems, openWoProblemModal, closeWoProblemModal, confirmResolveWoProblem,
         openDelayedWoDetail, closeDelayedWoDetail } from './pages/manager-view.js';
import { openAlertResolve, submitAlertResolve } from './pages/manager-alerts.js';
import { loadOpenOrders, setSectionSort, openOrderSortIcon,
         setRowColor, effectiveRowColor, openOrderRowClass, openOrderColorDotClass,
         loadReminderEmail, saveReminderEmail,
         openOrderStatusClass, chuteStatusClass, openOrderHasLine3,
         cancelAddModal, parsePasteRows, saveOpenOrderRow,
         moveToSection, bulkChangeStatus,
         startCellEdit, saveCellEdit, cancelCellEdit, deleteOpenOrder,
         toggleOpenOrderExpand,
         openWoDetailPanel, closeWoDetailPanel,
         woDeptBadgeClass, woStatusBadgeClass } from './pages/open-orders-view.js';
import { onRowMouseDown, onRowMouseEnter, onRowDragStart, onRowDragEnd,
         onSectionDragOver, onSectionDragLeave, onSectionDrop, clearRowSelection,
         onScrollAreaDragOver, onGripDragStart, onGripDragEnd,
         onDropZoneDragOver, clearDropZone, reorderDrop } from './pages/open-orders-drag.js';
import { loadInventoryItems, switchInventoryTab,
         openPullForm, closePullForm, submitPull,
         openAddItemForm, closeAddItemForm, submitAddItem,
         openEditItemForm, closeEditItemForm, submitEditItem,
         confirmDeleteInventoryItem,
         openPullHistory, closePullHistory,
         loadPoReceiveOrders, openPoReceiveItem, closePoReceiveItem, submitPoReceive,
         loadPoReceivedOrders, unreceivePoOrder } from './pages/inventory-view.js';
import { loadWoRequests, submitWoRequestForm, deleteWoRequestItem,
         openWoRequestDetail, closeWoRequestDetail,
         saveWoRequestDetail, sendToManagerApproval,
         saveWoRequestInlineFields,
         checkWoRequestPartMatch, acceptSoHint, dismissSoHint,
         openSendToForecast, closeSendToForecast, submitSendToForecast,
         handleWoFileUploadForRequest, openSubpartWoForm } from './pages/wo-request-view.js';
import { loadForecastedItems,
         openDeleteConfirm, cancelDeleteForecast, confirmDeleteForecast,
         openMoveBackConfirm, cancelMoveBack, confirmMoveBack } from './pages/wo-forecasting-view.js';
import { loadCreateWoItems, setAlereWoNumber, switchCreateWoTab, loadCreatedWoItems } from './pages/create-wo-view.js';
import { enterCompletedOrdersView, loadCompletedOrders, restoreCompletedOrder } from './pages/completed-orders-view.js';
import { loadPurchasingOrders, switchPurchasingTab,
         loadPurchasingCompleted, loadOrderEvents,
         openNewRequestForm, closeNewRequestForm, submitPurchasingRequest,
         onPurchasingPartBlur,
         openOrderDetail, closeOrderDetail, saveOrderDetail,
         loadPartUsageForOrder,
         loadOrderQuotes, saveQuote, addQuoteRow, removeQuoteRow,
         saveSteelField, saveSteelQuotes, addSteelQuote, toggleBestQuote, removeSteelQuote,
         toggleSteelStatusPicker, setSteelStatus,
         selectSteelQuoteForOrder, closeSteelOrderPanel, confirmSteelOrder,
         uploadSteelQuoteFile, openSteelQuoteFile, removeSteelQuoteFile } from './pages/purchasing-view.js';
import { completeOrder, submitReceiving } from './pages/purchasing-receive.js';
import { enterApprovalTab, approveOrder, cancelRevise, submitRevise } from './pages/purchasing-approval.js';
import { enterWoApprovalView, exitWoApprovalView, loadManagerPendingWoRequests,
         openManagerWoDetail, closeManagerWoDetail, saveManagerWoDetail,
         managerFinalApproveWo,
         openManagerWoSendBack, cancelManagerWoSendBack,
         submitManagerWoSendBack,
         loadManagerWoFiles, handleManagerWoFileUpload,
         handleManagerWoFileDelete } from './pages/wo-manager-approval.js';
import { uploadOrderAttachment, deleteOrderAttachment, loadOrderAttachments,
         loadPurchasingPartFiles } from './pages/purchasing-attachments.js';
import { openQuoteBuilder, closeQuoteBuilder, toggleQuoteOrder, submitQuote,
         stageQuoteFile, unstageQuoteFile,
         loadAllQuotes, openQuoteOrder, cancelQuoteOrder, submitQuoteOrder } from './pages/purchasing-quotes-view.js';
import { openSupplierCatalogFromHistory, loadSupplierCatalog,
         clearSupplierCatalog } from './pages/purchasing-research.js';
import { openRfqDraft, closeRfqDraft, copyRfqDraft,
         addOrderToRfq, removeOrderFromRfq } from './pages/purchasing-rfq.js';
import { enterPurchasingView, enterPoRequestView, enterApprovalQueueView } from './pages/splash-view.js';
import { enterPoForecastingView, exitPoForecastingView, loadPoForecast,
         openPoForecastDeleteConfirm, cancelPoForecastDelete, confirmPoForecastDelete,
         openPoForecastMoveBack, cancelPoForecastMoveBack, confirmPoForecastMoveBack,
         openPoForecastSend, closePoForecastSend, submitPoForecastSend,
         openForecastOrderDetail, checkForecastRevisits } from './pages/purchasing-forecast.js';

export function buildOpsExpose() {
    return {
        // Manager AI chat
        aiChatOpen:     store.aiChatOpen,
        aiChatLoading:  store.aiChatLoading,
        aiChatInput:    store.aiChatInput,
        aiChatMessages: store.aiChatMessages,

        // Manager
        assignCustomInput:    store.assignCustomInput,
        managerSubView:       store.managerSubView,
        priorityDept:         store.priorityDept,
        priorityOrders:       store.priorityOrders,
        delayedOrders:        store.delayedOrders,
        delayedOrdersByDept:  store.delayedOrdersByDept,
        kpiStats:             store.kpiStats,
        kpiByOperator:        store.kpiByOperator,
        kpiCycleTime:         store.kpiCycleTime,
        kpiHoldReasons:       store.kpiHoldReasons,
        kpiOldestWos:         store.kpiOldestWos,
        managerAlerts:        store.managerAlerts,
        delayedWoCount:       store.delayedWoCount,
        managerAlertCount:    store.managerAlertCount,
        managerTotalBadge:    store.managerTotalBadge,

        // WO Problems
        woProblems:                 store.woProblems,
        woProblemCount:             store.woProblemCount,
        woProblemModalOpen:         store.woProblemModalOpen,
        woProblemTarget:            store.woProblemTarget,
        woProblemResolution:        store.woProblemResolution,
        woProblemResolutionError:   store.woProblemResolutionError,
        woProblemResolverName:      store.woProblemResolverName,
        woProblemResolverNameError: store.woProblemResolverNameError,

        // Manager functions
        openManagerSection, loadKpiData, loadDelayedOrders,
        fetchPriorityOrders, updatePriority, updateAssignedOperator,
        handleAssignChange, submitCustomAssign, cancelCustomAssign,
        openNotesPanel, loadManagerAlerts,
        sendAiMessage, loadTimeReport,
        delayedWoDetailOpen: store.delayedWoDetailOpen,
        delayedWoDetail:     store.delayedWoDetail,
        openDelayedWoDetail, closeDelayedWoDetail,
        loadWoProblems, openWoProblemModal, closeWoProblemModal, confirmResolveWoProblem,
        alertResolveOpen:      store.alertResolveOpen,
        alertResolveTarget:    store.alertResolveTarget,
        alertResolveType:      store.alertResolveType,
        alertResolveBy:        store.alertResolveBy,
        alertResolveByError:   store.alertResolveByError,
        alertResolveText:      store.alertResolveText,
        alertResolveTextError: store.alertResolveTextError,
        openAlertResolve, submitAlertResolve,

        // Time Report
        timeReportSessions:     store.timeReportSessions,
        timeReportFrom:         store.timeReportFrom,
        timeReportTo:           store.timeReportTo,
        timeReportTab:          store.timeReportTab,
        timeReportExpandedWo:   store.timeReportExpandedWo,
        timeReportExpandedPart: store.timeReportExpandedPart,
        timeReportByWo:         store.timeReportByWo,
        timeReportByPart:       store.timeReportByPart,

        // WO Requests
        woRequests:           store.woRequests,
        woRequestsLoading:    store.woRequestsLoading,
        woRequestForm:        store.woRequestForm,
        woRequestFormErrors:  store.woRequestFormErrors,
        woRequestSearch:      store.woRequestSearch,
        filteredWoRequests:   store.filteredWoRequests,
        selectedWoRequest:    store.selectedWoRequest,
        woRequestReadOnly:    store.woRequestReadOnly,
        woRequestDetailForm:  store.woRequestDetailForm,
        woRequestInlineState:        store.woRequestInlineState,
        woRequestSoHint:             store.woRequestSoHint,
        woRequestDefaultsApplied:    store.woRequestDefaultsApplied,
        woRequestHistoryLoading:         store.woRequestHistoryLoading,
        woRequestParentUsageLoading:     store.woRequestParentUsageLoading,
        woRequestHistoryLoading36mo:     store.woRequestHistoryLoading36mo,
        woRequestParentUsageLoading36mo: store.woRequestParentUsageLoading36mo,
        woRequestEstQtyInStock36mo:      store.woRequestEstQtyInStock36mo,
        woRequestSuggestedQty36mo:       store.woRequestSuggestedQty36mo,
        woRequestLastMade:               store.woRequestLastMade,
        woRequestSubparts:             store.woRequestSubparts,
        woRequestSubpartsLoading:      store.woRequestSubpartsLoading,
        woRequestSubpartsExpanded:     store.woRequestSubpartsExpanded,
        woRequestSubpartMode:          store.woRequestSubpartMode,
        woRequestSubpartBins:          store.woRequestSubpartBins,
        woRequestSubpartDescs:         store.woRequestSubpartDescs,
        woRequestSubpartForms:         store.woRequestSubpartForms,
        woRequestSubpartStats:         store.woRequestSubpartStats,
        woRequestSubpartEstHave:       store.woRequestSubpartEstHave,
        woRequestEstQtyInStock:      store.woRequestEstQtyInStock,
        woRequestSuggestedQty:       store.woRequestSuggestedQty,
        woRequestStockWarning:       store.woRequestStockWarning,
        enterWoRequestView,
        submitWoRequestForm,
        deleteWoRequestItem,
        openWoRequestDetail,
        closeWoRequestDetail,
        saveWoRequestDetail,
        sendToManagerApproval,
        saveWoRequestInlineFields,
        checkWoRequestPartMatch, acceptSoHint, dismissSoHint,
        openSubpartWoForm,
        openSendToForecast, closeSendToForecast, submitSendToForecast,
        handleWoFileUploadForRequest,
        sendToForecastOpen:   store.sendToForecastOpen,
        sendToForecastTarget: store.sendToForecastTarget,
        sendToForecastForm:   store.sendToForecastForm,
        sendToForecastErrors: store.sendToForecastErrors,

        // WO Forecasting
        forecastingItems:  store.forecastingItems,
        forecastingLoading: store.forecastingLoading,
        forecastDeleteId:  store.forecastDeleteId,
        forecastMoveBackId: store.forecastMoveBackId,
        enterWoForecastingView, loadForecastedItems,
        openDeleteConfirm, cancelDeleteForecast, confirmDeleteForecast,
        openMoveBackConfirm, cancelMoveBack, confirmMoveBack,

        // Create WO
        createWoItems:       store.createWoItems,
        createWoItemsGrouped: store.createWoItemsGrouped,
        createWoLoading:     store.createWoLoading,
        createWoInlineState: store.createWoInlineState,
        createWoTab:         store.createWoTab,
        createdWoItems:         store.createdWoItems,
        createdWoItemsGrouped:  store.createdWoItemsGrouped,
        enterCreateWoView, loadCreateWoItems, setAlereWoNumber, switchCreateWoTab, loadCreatedWoItems,

        // Inventory
        inventoryMode:          store.inventoryMode,
        inventoryTab:           store.inventoryTab,
        inventoryItems:         store.inventoryItems,
        inventoryLoading:       store.inventoryLoading,
        inventorySearch:        store.inventorySearch,
        filteredInventoryItems: store.filteredInventoryItems,
        pullFormOpen:           store.pullFormOpen,
        pullFormTarget:         store.pullFormTarget,
        pullForm:               store.pullForm,
        pullFormErrors:         store.pullFormErrors,
        addItemFormOpen:        store.addItemFormOpen,
        addItemForm:            store.addItemForm,
        addItemFormErrors:      store.addItemFormErrors,
        editItemFormOpen:       store.editItemFormOpen,
        editItemFormTarget:     store.editItemFormTarget,
        editItemForm:           store.editItemForm,
        editItemFormErrors:     store.editItemFormErrors,
        pullHistoryOpen:        store.pullHistoryOpen,
        pullHistoryTarget:      store.pullHistoryTarget,
        pullHistoryItems:       store.pullHistoryItems,
        pullHistoryLoading:     store.pullHistoryLoading,
        // PO Receive
        poReceiveOrders:           store.poReceiveOrders,
        poReceiveLoading:          store.poReceiveLoading,
        poReceiveTab:              store.poReceiveTab,
        poReceiveOpen:             store.poReceiveOpen,
        poReceiveItem:             store.poReceiveItem,
        poReceiveSaving:           store.poReceiveSaving,
        poReceiveForm:             store.poReceiveForm,
        filteredPoReceiveOrders:   store.filteredPoReceiveOrders,
        poReceiveCounts:           store.poReceiveCounts,
        poReceiveSearch:           store.poReceiveSearch,
        // PO Already Received
        poReceivedOrders:          store.poReceivedOrders,
        poReceivedLoading:         store.poReceivedLoading,
        poReceiveShowReceived:     store.poReceiveShowReceived,
        filteredPoReceivedOrders:  store.filteredPoReceivedOrders,
        poReceivedCounts:          store.poReceivedCounts,
        inventoryTabs: INVENTORY_TABS,
        enterInventoryView, enterPoReceiveView, switchInventoryTab,
        openPullForm, closePullForm, submitPull,
        openAddItemForm, closeAddItemForm, submitAddItem,
        openEditItemForm, closeEditItemForm, submitEditItem,
        confirmDeleteInventoryItem,
        openPullHistory, closePullHistory,
        loadPoReceiveOrders, openPoReceiveItem, closePoReceiveItem, submitPoReceive,
        loadPoReceivedOrders, unreceivePoOrder,

        // Completed Orders
        completedOrders:        store.completedOrders,
        completedOrdersLoading: store.completedOrdersLoading,
        enterCompletedOrdersView, loadCompletedOrders, restoreCompletedOrder,

        // Purchasing
        purchasingTab:              store.purchasingTab,
        purchasingOrders:           store.purchasingOrders,
        purchasingLoading:          store.purchasingLoading,
        filteredPurchasingOrders:    store.filteredPurchasingOrders,
        steelOrdersByLocation:       store.steelOrdersByLocation,
        partOrdersByLocation:        store.partOrdersByLocation,
        supplyOrdersByLocation:      store.supplyOrdersByLocation,
        poForecastOrdersByLocation:  store.poForecastOrdersByLocation,
        approvalOrdersByLocation:    store.approvalOrdersByLocation,
        steelStatusPickerOpen:      store.steelStatusPickerOpen,
        steelOrderPanelOpen:        store.steelOrderPanelOpen,
        steelOrderSaving:           store.steelOrderSaving,
        steelOrderErrors:           store.steelOrderErrors,
        steelOrderForm:             store.steelOrderForm,
        purchasingTabCounts:        store.purchasingTabCounts,
        purchasingRequestModalOpen:  store.purchasingRequestModalOpen,
        purchasingRequestSaving:     store.purchasingRequestSaving,
        purchasingRequestForm:       store.purchasingRequestForm,
        purchasingRequestFormErrors: store.purchasingRequestFormErrors,
        purchasingDetailOpen:           store.purchasingDetailOpen,
        purchasingDetailOrder:          store.purchasingDetailOrder,
        purchasingDetailSection:        store.purchasingDetailSection,
        purchasingDetailSaving:         store.purchasingDetailSaving,
        purchasingDetailAutoSaved:      store.purchasingDetailAutoSaved,
        purchasingReceiveSaving:        store.purchasingReceiveSaving,
        purchasingDetailForm:           store.purchasingDetailForm,
        purchasingReceiveForm:          store.purchasingReceiveForm,
        purchasingDetailEvents:         store.purchasingDetailEvents,
        purchasingDetailEventsLoading:  store.purchasingDetailEventsLoading,
        purchasingPartUsage:              store.purchasingPartUsage,
        purchasingPartUsageLoading:       store.purchasingPartUsageLoading,
        purchasingPartParentUsage:        store.purchasingPartParentUsage,
        purchasingPartParentUsageLoading: store.purchasingPartParentUsageLoading,
        purchasingPartEstQtyInStock:      store.purchasingPartEstQtyInStock,
        purchasingPartSuggestedQty:       store.purchasingPartSuggestedQty,
        purchasingPartPurchaseHistory:        store.purchasingPartPurchaseHistory,
        purchasingPartPurchaseHistoryLoading: store.purchasingPartPurchaseHistoryLoading,
        purchasingPartPurchaseHistoryError:   store.purchasingPartPurchaseHistoryError,
        purchasingPartUsage36mo:              store.purchasingPartUsage36mo,
        purchasingPartUsageLoading36mo:       store.purchasingPartUsageLoading36mo,
        purchasingPartParentUsage36mo:        store.purchasingPartParentUsage36mo,
        purchasingPartParentUsageLoading36mo: store.purchasingPartParentUsageLoading36mo,
        purchasingPartEstQtyInStock36mo:      store.purchasingPartEstQtyInStock36mo,
        purchasingPartSuggestedQty36mo:       store.purchasingPartSuggestedQty36mo,
        purchasingDetailQuotes:         store.purchasingDetailQuotes,
        purchasingDetailQuotesLoading:  store.purchasingDetailQuotesLoading,
        orderAttachments:          store.orderAttachments,
        orderAttachmentsLoading:   store.orderAttachmentsLoading,
        orderAttachmentsUploading: store.orderAttachmentsUploading,
        quoteBuilderOpen:            store.quoteBuilderOpen,
        quoteBuilderSaving:          store.quoteBuilderSaving,
        quoteBuilderSelectedOrders:  store.quoteBuilderSelectedOrders,
        quoteBuilderItems:           store.quoteBuilderItems,
        quoteBuilderForm:            store.quoteBuilderForm,
        quoteBuilderPendingFiles:    store.quoteBuilderPendingFiles,
        allQuotes:                   store.allQuotes,
        allQuotesLoading:            store.allQuotesLoading,
        quoteOrderingId:             store.quoteOrderingId,
        quoteOrderPoNum:             store.quoteOrderPoNum,
        quoteOrderSaving:            store.quoteOrderSaving,
        purchasingCompletedOrders:      store.purchasingCompletedOrders,
        purchasingCompletedLoading:     store.purchasingCompletedLoading,
        purchasingCompletedFrom:        store.purchasingCompletedFrom,
        purchasingCompletedTo:          store.purchasingCompletedTo,
        approvalOrders:          store.approvalOrders,
        approvalManagerAuthed:   store.approvalManagerAuthed,
        approvalPinInput:        store.approvalPinInput,
        approvalPinError:        store.approvalPinError,
        approvalReviseOpen:      store.approvalReviseOpen,
        approvalReviseNote:      store.approvalReviseNote,
        // PO Forecasting
        poForecastOrders:     store.poForecastOrders,
        poForecastLoading:    store.poForecastLoading,
        poForecastDeleteId:   store.poForecastDeleteId,
        poForecastMoveBackId: store.poForecastMoveBackId,
        poForecastSendOpen:   store.poForecastSendOpen,
        poForecastSendSaving: store.poForecastSendSaving,
        poForecastSendErrors: store.poForecastSendErrors,
        poForecastSendForm:   store.poForecastSendForm,
        enterPoForecastingView, exitPoForecastingView, loadPoForecast,
        openPoForecastDeleteConfirm, cancelPoForecastDelete, confirmPoForecastDelete,
        openPoForecastMoveBack, cancelPoForecastMoveBack, confirmPoForecastMoveBack,
        openPoForecastSend, closePoForecastSend, submitPoForecastSend,
        openForecastOrderDetail, checkForecastRevisits,

        enterPurchasingView, enterPoRequestView, enterApprovalQueueView, loadPurchasingOrders, switchPurchasingTab,
        loadPurchasingCompleted, loadOrderEvents,
        openNewRequestForm, closeNewRequestForm, submitPurchasingRequest, onPurchasingPartBlur,
        openOrderDetail, closeOrderDetail, saveOrderDetail, completeOrder, submitReceiving, loadPartUsageForOrder,
        loadOrderQuotes, saveQuote, addQuoteRow, removeQuoteRow,
        saveSteelField, saveSteelQuotes, addSteelQuote, toggleBestQuote, removeSteelQuote,
        toggleSteelStatusPicker, setSteelStatus,
        selectSteelQuoteForOrder, closeSteelOrderPanel, confirmSteelOrder,
        uploadSteelQuoteFile, openSteelQuoteFile, removeSteelQuoteFile,
        uploadOrderAttachment, deleteOrderAttachment, loadOrderAttachments, loadPurchasingPartFiles,
        enterApprovalTab, approveOrder, cancelRevise, submitRevise,
        openRfqDraft, closeRfqDraft, copyRfqDraft, addOrderToRfq, removeOrderFromRfq,
        rfqDraftOpen:     store.rfqDraftOpen,
        rfqDraftSubject:  store.rfqDraftSubject,
        rfqDraftText:     store.rfqDraftText,
        rfqDraftHtml:     store.rfqDraftHtml,
        rfqDraftCopied:   store.rfqDraftCopied,
        rfqDraftOrders:   store.rfqDraftOrders,
        rfqPickerOpen:    store.rfqPickerOpen,
        rfqPickerSearch:  store.rfqPickerSearch,
        rfqPickerResults: store.rfqPickerResults,

        // Manager WO Approval Queue
        managerWoApprovalList:    store.managerWoApprovalList,
        managerWoApprovalLoading: store.managerWoApprovalLoading,
        managerWoSelectedRequest: store.managerWoSelectedRequest,
        managerWoDetailForm:      store.managerWoDetailForm,
        managerWoSendBackOpen:    store.managerWoSendBackOpen,
        managerWoSendBackNote:    store.managerWoSendBackNote,
        managerWoApprovalCount:   store.managerWoApprovalCount,
        enterWoApprovalView, exitWoApprovalView, loadManagerPendingWoRequests,
        openManagerWoDetail, closeManagerWoDetail, saveManagerWoDetail,
        managerFinalApproveWo,
        openManagerWoSendBack, cancelManagerWoSendBack, submitManagerWoSendBack,
        loadManagerWoFiles, handleManagerWoFileUpload, handleManagerWoFileDelete,

        openQuoteBuilder, closeQuoteBuilder, toggleQuoteOrder, submitQuote,
        stageQuoteFile, unstageQuoteFile,
        loadAllQuotes, openQuoteOrder, cancelQuoteOrder, submitQuoteOrder,
        supplierCatalogLoading:  store.supplierCatalogLoading,
        supplierCatalogParts:    store.supplierCatalogParts,
        supplierCatalogCoid:     store.supplierCatalogCoid,
        supplierCatalogName:     store.supplierCatalogName,
        supplierCatalogSearch:   store.supplierCatalogSearch,
        supplierCatalogChoices:  store.supplierCatalogChoices,
        filteredSupplierCatalog: store.filteredSupplierCatalog,
        openSupplierCatalogFromHistory, loadSupplierCatalog, clearSupplierCatalog,

        // Open Orders
        openOrders:               store.openOrders,
        openOrdersLoading:        store.openOrdersLoading,
        openOrdersSort:           store.openOrdersSort,
        openOrderSections:        store.openOrderSections,
        openOrderColorPickerRow:  store.openOrderColorPickerRow,
        openOrderEditingCell:     store.openOrderEditingCell,
        openOrderEditingValue:    store.openOrderEditingValue,
        openOrderSelectedIds:     store.openOrderSelectedIds,
        openOrderBulkStatus:      store.openOrderBulkStatus,
        openOrderDragOverSection: store.openOrderDragOverSection,
        openOrderDropZoneTarget:  store.openOrderDropZoneTarget,
        openOrderExpandedCols:    store.openOrderExpandedCols,
        openOrderAddModalOpen:    store.openOrderAddModalOpen,
        openOrderAddMode:         store.openOrderAddMode,
        openOrderAddForm:         store.openOrderAddForm,
        openOrderAddFormErrors:   store.openOrderAddFormErrors,
        openOrderAddPasteText:    store.openOrderAddPasteText,
        openOrderAddPasteRows:    store.openOrderAddPasteRows,
        openOrderStatuses:        OPEN_ORDER_STATUSES,
        chutePartStatuses:        CHUTE_PART_STATUSES,
        openOrderSortFields:      OPEN_ORDER_SORT_FIELDS,
        enterOpenOrdersView,
        loadOpenOrders,
        setSectionSort,
        openOrderSortIcon,
        setRowColor,
        effectiveRowColor,
        openOrderRowClass,
        reminderEmailModalOpen: store.reminderEmailModalOpen,
        reminderEmail:          store.reminderEmail,
        reminderEmailSaving:    store.reminderEmailSaving,
        saveReminderEmail,
        headerLinks:          store.headerLinks,
        headerLinksModalOpen: store.headerLinksModalOpen,
        headerLinksSaving:    store.headerLinksSaving,
        saveHeaderLinks,
        splashLinks:          store.splashLinks,
        splashLinksModalOpen: store.splashLinksModalOpen,
        splashLinksSaving:    store.splashLinksSaving,
        saveSplashLinks,
        openOrderColorDotClass,
        openOrderStatusClass,
        chuteStatusClass,
        openOrderHasLine3,
        cancelAddModal,
        parsePasteRows,
        saveOpenOrderRow,
        moveToSection, bulkChangeStatus,
        onRowMouseDown, onRowMouseEnter, onRowDragStart, onRowDragEnd,
        onSectionDragOver, onSectionDragLeave, onSectionDrop, clearRowSelection,
        onScrollAreaDragOver, onGripDragStart, onGripDragEnd,
        onDropZoneDragOver, clearDropZone, reorderDrop,
        startCellEdit, saveCellEdit, cancelCellEdit, deleteOpenOrder,
        toggleOpenOrderExpand,
        openOrderWoPanel:        store.openOrderWoPanel,
        openOrderWoPanelOrders:  store.openOrderWoPanelOrders,
        openOrderWoPanelLoading: store.openOrderWoPanelLoading,
        openWoDetailPanel, closeWoDetailPanel,
        woDeptBadgeClass, woStatusBadgeClass,
    };
}
